bind-addr: 0.0.0.0:8080
auth: password
password: "{{ code_server_password }}"
cert: false
user-data-dir: /home/coder/.local/share/code-server
extensions-dir: /home/coder/.local/share/code-server/extensions
