basic_packages:
  - bat
  - curl
  - delta
  - docker
  - docker-compose
  - eza
  - fzf
  - git
  - htop
  - libjpeg-dev
  - libxtst-dev
  - lua5.3
  - lsof
  - mmv
  - python3-pip
  - ripgrep
  - rsync
  - starship
  - stow
  - tree
  - ufw
  - vifm
  - zlib1g-dev
  - zsh

nvim_deps:
  - ninja-build
  - gettext
  - libtool
  - libtool-bin
  - autoconf
  - automake
  - cmake
  - g++
  - pkg-config
  - unzip
  - doxygen
