- name: Create docker group
  group:
    name: docker
    state: present

- name: Ensure user {{ username }} exists
  user:
    name: "{{ username }}"
    state: present
    groups:
      - sudo
      - docker
    system: true
    createhome: true
    home: "/home/{{ username }}"
