- name: Custom dotfiles
  when: dotfiles_repo is defined
  block:
    - name: Clone dotfiles
      import_tasks: dotfiles.yml

    - name: Install basick packages
      import_tasks: install.yml

    - name: Copy configs for root
      become: true
      import_tasks: root.yml
