- name: Create and chown website dir
  file:
    path: "/home/{{ username }}/website"
    state: directory
    mode: 0755

- name: Sample index
  copy:
    dest: "/home/{{ username }}/website/index.html"
    content: |
      <head>
        <title>Your Website</title>
        <!-- Umami script for analytics goes here -->
        <script defer src="https://umami.{{domain}}/script.js" data-website-id="your-data-website-id"></script>
      </head>
      <body>
        <h1>
          Hello World!
        </h1>
      </body>
    mode: 0644
