- name: Basic Server Setup
  hosts: all
  vars_files:
    - ../vars/main.yml
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600 # Valid for 1 hour

    - name: Set the system timezone to UTC
      timezone:
        name: UTC

    - name: Add a super user
      user:
        name: "{{ admin_user }}"
        state: present
        groups: sudo
        shell: /bin/bash

    - name: Configure SSH for the new user
      authorized_key:
        user: "{{ admin_user }}"
        state: present
        key: "{{ ssh_public_key }}"
      register: ssh_key_result

    - name: Mark SSH config as changed if key was added
      set_fact:
        ssh_config_changed: true
      when: ssh_key_result.changed

    - name: Disable root SSH access
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      notify:
        - Restart SSH

  handlers:
    - name: Ensure SSH service is restarted only when necessary
      service:
        name: ssh
        state: restarted
      when: ssh_config_changed is defined and ssh_config_changed
