- name: Ensure lsb-release is installed
  apt:
    name: lsb-release
    state: present
  tags: nginx

- name: Explicitly gather facts
  setup:
    filter: ansible_distribution*
  tags: nginx

- name: Download NGINX GPG key
  shell:
    cmd: |
      set -o pipefail
      curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor \
        | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
    executable: /bin/bash
  changed_when: true

- name: Add NGINX repository to sources.list.d
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/debian {{ ansible_distribution_release }} nginx"
    state: present
    filename: nginx

- name: Install packages
  import_role:
    name: common_roles/install_latest
  vars:
    packages:
      - "nginx"
      - "python3-certbot-nginx"
