- name: Clear existing servers
  block:
    - name: Rm sites-enabled
      file:
        state: absent
        path: '/etc/nginx/sites-enabled'

    - name: Mkdir sites-enabled
      file:
        state: directory
        path: '/etc/nginx/sites-enabled'
        mode: 0755

- name: Get onion address
  slurp:
    src: '/var/lib/tor/hidden_service/hostname'
  register: onion_address

- name: Config website server
  template:
    src: 'nginx-website'
    dest: '/etc/nginx/sites-enabled/website'
    mode: 0644

- name: Config proxy server for umami
  vars:
    subdom: '{{ service.umami.subdomain }}'
    port: '{{ service.umami.port }}'
  template:
    src: nginx-service
    dest: '/etc/nginx/sites-enabled/{{ service.umami.subdomain }}'
    mode: 0644

- name: Config proxy server for code-server (public domain)
  when: expose_code_server_public | default(false)
  vars:
    subdom: '{{ service.code_server.subdomain }}'
    port: '{{ service.code_server.port }}'
    nginx_cloudflare_allowlist: true
  template:
    src: nginx-service
    dest: '/etc/nginx/sites-enabled/{{ service.code_server.subdomain }}'
    mode: 0644

- name: Config proxy server for code-server (Tailscale domain)
  when: expose_code_server_tailscale | default(true)
  vars:
    subdom: '{{ service.code_server.subdomain }}'
    port: '{{ service.code_server.port }}'
    nginx_use_tailscale_certs: true
    nginx_tls_domain: '{{ tailscale_hostname }}'
  template:
    src: nginx-service-tailscale
    dest: '/etc/nginx/sites-enabled/{{ service.code_server.subdomain }}-tailscale'
    mode: 0644

- name: Enable and restart nginx
  service:
    name: nginx
    enabled: true
    state: restarted
